# Generated by Django 5.0 on 2023-12-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
