# Generated by Django 5.0 on 2023-12-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_quatity_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Catagory',
        ),
    ]
